//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class HotUpdateWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(HotUpdate), typeof(System.Object));
		L.RegFunction("New", _CreateHotUpdate);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("mReleaseVersion", get_mReleaseVersion, set_mReleaseVersion);
		L.RegVar("mMajorVersion", get_mMajorVersion, set_mMajorVersion);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateHotUpdate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				HotUpdate obj = new HotUpdate();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: HotUpdate.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mReleaseVersion(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, HotUpdate.mReleaseVersion);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mMajorVersion(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, HotUpdate.mMajorVersion);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mReleaseVersion(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			HotUpdate.mReleaseVersion = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mMajorVersion(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			HotUpdate.mMajorVersion = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

